algoritmo "semnome"
// Função :
// Autor :  Andrey
// Data : 22/08/2018
// Seção de Declarações 
var
AN, AA, IDA, ID2050 :inteiro
inicio
// Seção de Comandos 
escreval("Qual sua idade em 2050")
escreval("Digite o ano do nascimento")
leia(AN)
escreval("Digite o ano atual")
leia(AA)
IDA<- AA-AN
ID2050<- 2050-AN
escreval("A sua idade atual é", IDA, " e ", "sua idade em 2050 será", ID2050)

fimalgoritmo
