algoritmo "semnome"
// Função :
// Autor :  Andrey
// Data : 22/08/2018
// Seção de Declarações 
var
NA :caractere
B1, B2, B3, B4, media :real
inicio
// Seção de Comandos 
escreval("media do aluno")
escreval("Digite o nome do aluno")
leia(NA)
escreval("Digite a nota B1")
leia(B1)
escreval("Digite a nota B2")
leia(B2)
escreval("Digite a nota B3")
leia(B3)
escreval("Digite a nota B4")
leia(B4)
media<- (B1+B2+B3+B4)/4
escreval("A media do aluno", NA, "é:", media)



fimalgoritmo
